// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/politica-de-privacidade": {
    params: {};
  };
  "/termos-de-servico": {
    params: {};
  };
  "/politica-de-cookies": {
    params: {};
  };
  "/lgpd": {
    params: {};
  };
  "/pobre-goods-imprimir": {
    params: {};
  };
  "/galeria": {
    params: {};
  };
  "/en": {
    params: {};
  };
  "/en/blog": {
    params: {};
  };
  "/en/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/en/privacy-policy": {
    params: {};
  };
  "/en/terms-of-service": {
    params: {};
  };
  "/en/cookie-policy": {
    params: {};
  };
  "/en/lgpd": {
    params: {};
  };
  "/en/pobre-goods-imprimir": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/en/gallery": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/blog" | "/blog/:slug" | "/politica-de-privacidade" | "/termos-de-servico" | "/politica-de-cookies" | "/lgpd" | "/pobre-goods-imprimir" | "/galeria" | "/en" | "/en/blog" | "/en/blog/:slug" | "/en/privacy-policy" | "/en/terms-of-service" | "/en/cookie-policy" | "/en/lgpd" | "/en/pobre-goods-imprimir" | "/sitemap.xml" | "/en/gallery" | "/*";
  };
  "pages/LandingPage.tsx": {
    id: "pages/LandingPage";
    page: "/";
  } | {
    id: "landing-en";
    page: "/en";
  };
  "pages/BlogListPage.tsx": {
    id: "pages/BlogListPage";
    page: "/blog";
  } | {
    id: "blog-list-en";
    page: "/en/blog";
  };
  "pages/BlogPostPage.tsx": {
    id: "pages/BlogPostPage";
    page: "/blog/:slug";
  } | {
    id: "blog-post-en";
    page: "/en/blog/:slug";
  };
  "pages/PrivacyPolicyPage.tsx": {
    id: "pages/PrivacyPolicyPage";
    page: "/politica-de-privacidade";
  } | {
    id: "privacy-en";
    page: "/en/privacy-policy";
  };
  "pages/TermsOfServicePage.tsx": {
    id: "pages/TermsOfServicePage";
    page: "/termos-de-servico";
  } | {
    id: "terms-en";
    page: "/en/terms-of-service";
  };
  "pages/CookiePolicyPage.tsx": {
    id: "pages/CookiePolicyPage";
    page: "/politica-de-cookies";
  } | {
    id: "cookies-en";
    page: "/en/cookie-policy";
  };
  "pages/LGPDPage.tsx": {
    id: "pages/LGPDPage";
    page: "/lgpd";
  } | {
    id: "lgpd-en";
    page: "/en/lgpd";
  };
  "pages/PobreGoods.tsx": {
    id: "pages/PobreGoods";
    page: "/pobre-goods-imprimir";
  } | {
    id: "pobre-goods-en";
    page: "/en/pobre-goods-imprimir";
  };
  "pages/GalleryPage.tsx": {
    id: "pages/GalleryPage";
    page: "/galeria";
  } | {
    id: "gallery-en";
    page: "/en/gallery";
  };
  "pages/sitemap.xml.tsx": {
    id: "pages/sitemap.xml";
    page: "/sitemap.xml";
  };
  "pages/NotFoundPage.tsx": {
    id: "not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "pages/LandingPage": typeof import("./app/pages/LandingPage.tsx");
  "pages/BlogListPage": typeof import("./app/pages/BlogListPage.tsx");
  "pages/BlogPostPage": typeof import("./app/pages/BlogPostPage.tsx");
  "pages/PrivacyPolicyPage": typeof import("./app/pages/PrivacyPolicyPage.tsx");
  "pages/TermsOfServicePage": typeof import("./app/pages/TermsOfServicePage.tsx");
  "pages/CookiePolicyPage": typeof import("./app/pages/CookiePolicyPage.tsx");
  "pages/LGPDPage": typeof import("./app/pages/LGPDPage.tsx");
  "pages/PobreGoods": typeof import("./app/pages/PobreGoods.tsx");
  "pages/GalleryPage": typeof import("./app/pages/GalleryPage.tsx");
  "landing-en": typeof import("./app/pages/LandingPage.tsx");
  "blog-list-en": typeof import("./app/pages/BlogListPage.tsx");
  "blog-post-en": typeof import("./app/pages/BlogPostPage.tsx");
  "privacy-en": typeof import("./app/pages/PrivacyPolicyPage.tsx");
  "terms-en": typeof import("./app/pages/TermsOfServicePage.tsx");
  "cookies-en": typeof import("./app/pages/CookiePolicyPage.tsx");
  "lgpd-en": typeof import("./app/pages/LGPDPage.tsx");
  "pobre-goods-en": typeof import("./app/pages/PobreGoods.tsx");
  "pages/sitemap.xml": typeof import("./app/pages/sitemap.xml.tsx");
  "gallery-en": typeof import("./app/pages/GalleryPage.tsx");
  "not-found": typeof import("./app/pages/NotFoundPage.tsx");
};